package com.jokecamera.app

import android.content.Context
import android.content.SharedPreferences

/**
 * Data class representing a joke with setup and punchline
 */
data class Joke(
    val id: Int,
    val setup: String,
    val punchline: String
)

/**
 * Manages the collection of 1000 jokes, tracks which have been told,
 * and ensures no repeats until all jokes have been used.
 */
class JokeManager(context: Context) {
    
    private val prefs: SharedPreferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    private val jokes: List<Joke> = generateJokes()
    private val toldJokeIds: MutableSet<Int> = loadToldJokes()
    
    companion object {
        private const val PREFS_NAME = "joke_manager_prefs"
        private const val KEY_TOLD_JOKES = "told_jokes"
    }
    
    /**
     * Gets the next joke that hasn't been told yet.
     * If all jokes have been told, resets and starts over.
     */
    fun getNextJoke(): Joke {
        // If all jokes have been told, reset
        if (toldJokeIds.size >= jokes.size) {
            resetToldJokes()
        }
        
        // Find a joke that hasn't been told
        val availableJokes = jokes.filter { it.id !in toldJokeIds }
        val joke = availableJokes.random()
        
        // Mark as told
        toldJokeIds.add(joke.id)
        saveToldJokes()
        
        return joke
    }
    
    /**
     * Gets a specific joke by ID (for testing/preview)
     */
    fun getJokeById(id: Int): Joke? = jokes.find { it.id == id }
    
    /**
     * Gets the count of remaining untold jokes
     */
    fun getRemainingCount(): Int = jokes.size - toldJokeIds.size
    
    /**
     * Gets the total joke count
     */
    fun getTotalCount(): Int = jokes.size
    
    /**
     * Resets all jokes to untold status
     */
    fun resetToldJokes() {
        toldJokeIds.clear()
        saveToldJokes()
    }
    
    private fun loadToldJokes(): MutableSet<Int> {
        val stored = prefs.getStringSet(KEY_TOLD_JOKES, emptySet()) ?: emptySet()
        return stored.mapNotNull { it.toIntOrNull() }.toMutableSet()
    }
    
    private fun saveToldJokes() {
        prefs.edit()
            .putStringSet(KEY_TOLD_JOKES, toldJokeIds.map { it.toString() }.toSet())
            .apply()
    }
    
    /**
     * Generates 1000 classic jokes
     */
    private fun generateJokes(): List<Joke> {
        return listOf(
            // Classic One-Liners (1-100)
            Joke(1, "Why don't scientists trust atoms?", "Because they make up everything!"),
            Joke(2, "Why did the scarecrow win an award?", "Because he was outstanding in his field!"),
            Joke(3, "Why don't eggs tell jokes?", "They'd crack each other up!"),
            Joke(4, "What do you call a fake noodle?", "An impasta!"),
            Joke(5, "Why did the bicycle fall over?", "Because it was two-tired!"),
            Joke(6, "What do you call a bear with no teeth?", "A gummy bear!"),
            Joke(7, "Why can't you give Elsa a balloon?", "Because she will let it go!"),
            Joke(8, "What do you call a fish without eyes?", "A fsh!"),
            Joke(9, "Why did the golfer bring two pairs of pants?", "In case he got a hole in one!"),
            Joke(10, "What do you call a sleeping dinosaur?", "A dino-snore!"),
            Joke(11, "Why don't oysters donate to charity?", "Because they're shellfish!"),
            Joke(12, "What do you call a cow with no legs?", "Ground beef!"),
            Joke(13, "Why did the cookie go to the doctor?", "Because it felt crummy!"),
            Joke(14, "What do you call a dog that does magic tricks?", "A Labracadabrador!"),
            Joke(15, "Why couldn't the leopard play hide and seek?", "Because he was always spotted!"),
            Joke(16, "What do you call a boomerang that doesn't come back?", "A stick!"),
            Joke(17, "Why did the math book look so sad?", "Because it had too many problems!"),
            Joke(18, "What do you call a pig that does karate?", "A pork chop!"),
            Joke(19, "Why don't skeletons fight each other?", "They don't have the guts!"),
            Joke(20, "What do you call cheese that isn't yours?", "Nacho cheese!"),
            Joke(21, "Why did the tomato turn red?", "Because it saw the salad dressing!"),
            Joke(22, "What do you call a can opener that doesn't work?", "A can't opener!"),
            Joke(23, "Why did the stadium get hot after the game?", "All the fans left!"),
            Joke(24, "What do you call a snowman with a six-pack?", "An abdominal snowman!"),
            Joke(25, "Why don't eggs tell each other jokes?", "They'd crack up!"),
            Joke(26, "What do lawyers wear to court?", "Lawsuits!"),
            Joke(27, "Why did the banana go to the doctor?", "Because it wasn't peeling well!"),
            Joke(28, "What do you call a lazy kangaroo?", "A pouch potato!"),
            Joke(29, "Why did the gym close down?", "It just didn't work out!"),
            Joke(30, "What do you call a dinosaur that crashes their car?", "Tyrannosaurus Wrecks!"),
            Joke(31, "Why don't calendars ever win races?", "Their days are numbered!"),
            Joke(32, "What do you call a group of musical whales?", "An orca-stra!"),
            Joke(33, "Why did the coffee file a police report?", "It got mugged!"),
            Joke(34, "What do you call a belt made of watches?", "A waist of time!"),
            Joke(35, "Why did the invisible man turn down the job offer?", "He couldn't see himself doing it!"),
            Joke(36, "What do you call a deer with no eyes?", "No eye deer!"),
            Joke(37, "Why did the picture go to jail?", "Because it was framed!"),
            Joke(38, "What do you call a cow in an earthquake?", "A milkshake!"),
            Joke(39, "Why did the computer go to the doctor?", "Because it had a virus!"),
            Joke(40, "What do you call a train loaded with toffee?", "A chew chew train!"),
            Joke(41, "Why did the grape stop in the middle of the road?", "Because it ran out of juice!"),
            Joke(42, "What do you call a pile of cats?", "A meow-ntain!"),
            Joke(43, "Why don't mountains get cold?", "They wear snow caps!"),
            Joke(44, "What do you call a bee that can't make up its mind?", "A maybe!"),
            Joke(45, "Why did the orange stop?", "Because it ran out of juice!"),
            Joke(46, "What do you call a sleeping bull?", "A bulldozer!"),
            Joke(47, "Why did the clock get kicked out of class?", "Because it kept tocking!"),
            Joke(48, "What do you call a monkey in a minefield?", "A baboom!"),
            Joke(49, "Why did the chicken join a band?", "Because it had the drumsticks!"),
            Joke(50, "What do you call a cold dog?", "A chili dog!"),
            
            // Food and Restaurant Jokes (51-150)
            Joke(51, "Why did the chef go to therapy?", "He had too much on his plate!"),
            Joke(52, "What do you call a sad strawberry?", "A blueberry!"),
            Joke(53, "Why did the lemon stop rolling?", "It ran out of juice!"),
            Joke(54, "What do you call a cheese factory in the Middle East?", "Cheeses of Nazareth!"),
            Joke(55, "Why don't peppers make good basketball players?", "They always get jalapeño face!"),
            Joke(56, "What did the sushi say to the bee?", "Wasabi!"),
            Joke(57, "Why did the bread break up with the margarine?", "For a butter lover!"),
            Joke(58, "What do you call a pizza with just peppers on it?", "A pepper-only pizza!"),
            Joke(59, "Why did the hot dog turn down a role in a movie?", "The roll wasn't good enough!"),
            Joke(60, "What did the grape do when it got stepped on?", "It let out a little wine!"),
            Joke(61, "Why did the cucumber call 911?", "Because it was in a pickle!"),
            Joke(62, "What do you call a fake steak?", "A mis-steak!"),
            Joke(63, "Why did the donut go to the dentist?", "It needed a filling!"),
            Joke(64, "What do you call a sleeping pizza?", "A pizzzzza!"),
            Joke(65, "Why did the apple turnover?", "Because it saw the rhubarb pie!"),
            Joke(66, "What do you call a nervous vegetable?", "An anxious bean!"),
            Joke(67, "Why did the hamburger go to the gym?", "To get better buns!"),
            Joke(68, "What do you call a laughing jar of mayo?", "LMAYO!"),
            Joke(69, "Why did the melon jump into the lake?", "It wanted to be a watermelon!"),
            Joke(70, "What do you call a carrot that talks back?", "A fresh vegetable!"),
            Joke(71, "Why did the orange join the circus?", "It wanted to be a fruit loops!"),
            Joke(72, "What do you call a lazy baker?", "A loafer!"),
            Joke(73, "Why did the knife break up with the spoon?", "Because the fork was sharper!"),
            Joke(74, "What do you call a sad cup of coffee?", "Depresso!"),
            Joke(75, "Why did the butter go to therapy?", "It was on a roll!"),
            Joke(76, "What do you call a fancy fish?", "So-fish-ticated!"),
            Joke(77, "Why did the egg hide?", "It was a little chicken!"),
            Joke(78, "What do you call a baby potato?", "A tater tot!"),
            Joke(79, "Why did the soup become a detective?", "It was good at finding broth!"),
            Joke(80, "What do you call an avocado after it's been blessed?", "Holy guacamole!"),
            Joke(81, "Why did the cookie cry?", "Because its mother was a wafer so long!"),
            Joke(82, "What do you call a peanut in space?", "An astronut!"),
            Joke(83, "Why did the gum cross the road?", "It was stuck to the chicken's foot!"),
            Joke(84, "What do you call a vegetable with attitude?", "Sassy parsley!"),
            Joke(85, "Why did the toast feel confident?", "It was on a roll!"),
            Joke(86, "What do you call honey made by a queen?", "Royal jelly!"),
            Joke(87, "Why did the rice go to therapy?", "It had too much grain baggage!"),
            Joke(88, "What do you call a sleeping vegetable?", "A rest-aurant!"),
            Joke(89, "Why did the bacon laugh?", "Because the egg cracked a yolk!"),
            Joke(90, "What do you call an angry pea?", "Grump-pea!"),
            Joke(91, "Why did the ice cream truck break down?", "It had a meltdown!"),
            Joke(92, "What do you call a nervous salad?", "Shake salad!"),
            Joke(93, "Why did the soup take a vacation?", "It needed to simmer down!"),
            Joke(94, "What do you call a fruit that commits crime?", "A bad apple!"),
            Joke(95, "Why did the milk go to art school?", "To become cultured!"),
            Joke(96, "What do you call a well-dressed salad?", "A dress-ing!"),
            Joke(97, "Why did the cereal go to the party?", "To get toasted!"),
            Joke(98, "What do you call a polite vegetable?", "A pleas-pea!"),
            Joke(99, "Why did the corn stalk get mad?", "It was being ear-itated!"),
            Joke(100, "What do you call a suspicious apple?", "A-peeling!"),
            
            // Animal Jokes (101-250)
            Joke(101, "Why do cows wear bells?", "Because their horns don't work!"),
            Joke(102, "What do you call an alligator in a vest?", "An investigator!"),
            Joke(103, "Why do seagulls fly over the sea?", "Because if they flew over the bay, they'd be bagels!"),
            Joke(104, "What do you call a fish wearing a bowtie?", "So-fish-ticated!"),
            Joke(105, "Why don't elephants use computers?", "They're afraid of the mouse!"),
            Joke(106, "What do you call a snake wearing a hard hat?", "A boa constructor!"),
            Joke(107, "Why do birds fly south for winter?", "It's too far to walk!"),
            Joke(108, "What do you call a penguin in the desert?", "Lost!"),
            Joke(109, "Why are frogs so happy?", "They eat whatever bugs them!"),
            Joke(110, "What do you call a rabbit with fleas?", "Bugs Bunny!"),
            Joke(111, "Why did the chicken go to the seance?", "To get to the other side!"),
            Joke(112, "What do you call a cat that likes water?", "A catfish!"),
            Joke(113, "Why do pandas like old movies?", "Because they're in black and white!"),
            Joke(114, "What do you call a lazy baby kangaroo?", "A pouch potato!"),
            Joke(115, "Why did the bee get married?", "Because he found his honey!"),
            Joke(116, "What do you call a pig that knows karate?", "Pork chop!"),
            Joke(117, "Why do hummingbirds hum?", "Because they forgot the words!"),
            Joke(118, "What do you call a deer with no eyes and no legs?", "Still no eye deer!"),
            Joke(119, "Why did the duck cross the playground?", "To get to the other slide!"),
            Joke(120, "What do you call a cow that eats your grass?", "A lawn moo-er!"),
            Joke(121, "Why are cats bad storytellers?", "Because they only have one tale!"),
            Joke(122, "What do you call a horse that lives next door?", "A neigh-bor!"),
            Joke(123, "Why did the turkey join the band?", "Because it had the drumsticks!"),
            Joke(124, "What do you call a bear in the rain?", "A drizzly bear!"),
            Joke(125, "Why do fish live in salt water?", "Because pepper makes them sneeze!"),
            Joke(126, "What do you call a monkey that loves chips?", "A chipmunk!"),
            Joke(127, "Why did the owl invite friends over?", "He didn't want to be owl by himself!"),
            Joke(128, "What do you call a sheep with no head and no legs?", "A cloud!"),
            Joke(129, "Why are dolphins so smart?", "Within three hours they can train a human to throw fish!"),
            Joke(130, "What do you call a dinosaur with an extensive vocabulary?", "A thesaurus!"),
            Joke(131, "Why did the spider go to computer class?", "To improve its website!"),
            Joke(132, "What do you call a dog magician?", "A Labracadabrador!"),
            Joke(133, "Why don't ants get sick?", "Because they have little antibodies!"),
            Joke(134, "What do you call a fly without wings?", "A walk!"),
            Joke(135, "Why did the lion eat the tightrope walker?", "He wanted a well-balanced meal!"),
            Joke(136, "What do you call a bird that's afraid to fly?", "Chicken!"),
            Joke(137, "Why are elephants so wrinkled?", "Have you ever tried to iron one?"),
            Joke(138, "What do you call a snail on a ship?", "A snailor!"),
            Joke(139, "Why did the horse go behind the tree?", "To change his jockeys!"),
            Joke(140, "What do you call a cat on the beach at Christmas?", "Sandy Claws!"),
            Joke(141, "Why don't crabs give to charity?", "Because they're shellfish!"),
            Joke(142, "What do you call a cow with a twitch?", "Beef jerky!"),
            Joke(143, "Why did the rooster cross the road?", "To prove he wasn't chicken!"),
            Joke(144, "What do you call a grumpy cow?", "Moody!"),
            Joke(145, "Why are giraffes so slow to apologize?", "It takes a long time for them to swallow their pride!"),
            Joke(146, "What do you call a frog with no back legs?", "Unhoppy!"),
            Joke(147, "Why did the cat sit on the computer?", "To keep an eye on the mouse!"),
            Joke(148, "What do you call a camel with no humps?", "Humphrey!"),
            Joke(149, "Why do elephants never forget?", "Because nobody ever tells them anything!"),
            Joke(150, "What do you call a snake that bakes?", "A pie-thon!"),
            Joke(151, "Why did the octopus beat the shark in a fight?", "Because it was well armed!"),
            Joke(152, "What do you call a group of disorganized cats?", "A cat-astrophe!"),
            Joke(153, "Why don't lobsters share?", "They're shellfish!"),
            Joke(154, "What do you call a dinosaur that crashes everything?", "Tyrannosaurus Wrecks!"),
            Joke(155, "Why did the elephant quit the circus?", "He was tired of working for peanuts!"),
            Joke(156, "What do you call a mosquito in a tin suit?", "A bite in shining armor!"),
            Joke(157, "Why do bees have sticky hair?", "Because they use honeycombs!"),
            Joke(158, "What do you call a bull taking a nap?", "A bulldozer!"),
            Joke(159, "Why did the pelican get kicked out of the restaurant?", "Because his bill was too big!"),
            Joke(160, "What do you call a sheep covered in chocolate?", "A candy baa!"),
            Joke(161, "Why don't koalas count as bears?", "They don't have the koalafications!"),
            Joke(162, "What do you call a hen looking at lettuce?", "Chicken Caesar salad!"),
            Joke(163, "Why did the pony cough?", "He was a little horse!"),
            Joke(164, "What do you call a turtle that flies?", "A shell-icopter!"),
            Joke(165, "Why are cats good at video games?", "Because they have nine lives!"),
            Joke(166, "What do you call a cow that just gave birth?", "De-calf-inated!"),
            Joke(167, "Why did the parrot wear a raincoat?", "So he would be polyunsaturated!"),
            Joke(168, "What do you call a dog that meditates?", "Aware wolf!"),
            Joke(169, "Why don't bears wear shoes?", "Because they like to go bear-foot!"),
            Joke(170, "What do you call a zebra with no stripes?", "A horse!"),
            Joke(171, "Why did the butterfly go to the dance?", "Because it was a moth ball!"),
            Joke(172, "What do you call a pig with laryngitis?", "Disgruntled!"),
            Joke(173, "Why are fish easy to weigh?", "Because they have their own scales!"),
            Joke(174, "What do you call a duck that steals?", "A robber ducky!"),
            Joke(175, "Why did the hippo break up with the zoo?", "He needed more space!"),
            Joke(176, "What do you call a gorilla wearing headphones?", "Anything you want, he can't hear you!"),
            Joke(177, "Why don't tigers like fast food?", "Because they can't catch it!"),
            Joke(178, "What do you call a rabbit that tells jokes?", "A funny bunny!"),
            Joke(179, "Why did the skunk cross the road?", "To get to the odor side!"),
            Joke(180, "What do you call a penguin in the Sahara?", "Lost!"),
            Joke(181, "Why are parrots good at improv?", "They're always winging it!"),
            Joke(182, "What do you call a dog that does chemistry?", "A lab!"),
            Joke(183, "Why did the frog take the bus to work?", "His car got toad away!"),
            Joke(184, "What do you call a snake that works for the government?", "A civil serpent!"),
            Joke(185, "Why don't chickens play baseball?", "They're too afraid of the fowl balls!"),
            Joke(186, "What do you call a bird that runs the country?", "A Pres-eagle-dent!"),
            Joke(187, "Why did the crow sit on the telephone wire?", "To make a long distance caw!"),
            Joke(188, "What do you call a clam that doesn't share?", "A selfish shellfish!"),
            Joke(189, "Why are spiders great baseball players?", "Because they know how to catch flies!"),
            Joke(190, "What do you call a buffalo at the beach?", "Sandy!"),
            Joke(191, "Why did the mouse stay home?", "Because it was raining cats and dogs!"),
            Joke(192, "What do you call a whale that plays guitar?", "A rock star fish!"),
            Joke(193, "Why don't grasshoppers watch football?", "They prefer cricket!"),
            Joke(194, "What do you call a squirrel that's obsessed with facts?", "A know-it-owl!"),
            Joke(195, "Why did the salmon blush?", "Because it saw the ocean's bottom!"),
            Joke(196, "What do you call a lizard that sings?", "A rap-tile!"),
            Joke(197, "Why are peacocks bad at keeping secrets?", "They're always showing off!"),
            Joke(198, "What do you call a cat in a station wagon?", "A car-pet!"),
            Joke(199, "Why did the worm cross the playground?", "To get to the other slide!"),
            Joke(200, "What do you call a bat that likes coffee?", "Decaff-inated!"),
            Joke(201, "Why did the goat join a band?", "Because he had great chops!"),
            Joke(202, "What do you call a sheep that can sing?", "Lady Baa Baa!"),
            Joke(203, "Why don't birds get lost?", "They always wing it!"),
            Joke(204, "What do you call a raccoon in a trash can?", "At home!"),
            Joke(205, "Why did the llama cross the road?", "To prove he wasn't a chicken!"),
            Joke(206, "What do you call a dog that likes bubble baths?", "A shampoo-dle!"),
            Joke(207, "Why are owls always invited to bird parties?", "Because they're a hoot!"),
            Joke(208, "What do you call a hamster with a top hat?", "Abrahamster Lincoln!"),
            Joke(209, "Why did the beaver leave the dam?", "He just couldn't build up the interest!"),
            Joke(210, "What do you call a fast bunny?", "A hot cross bunny!"),
            Joke(211, "Why don't leopards play poker?", "Too many cheetahs!"),
            Joke(212, "What do you call a lamb doing karate?", "A lamb chop!"),
            Joke(213, "Why did the caterpillar study?", "To become a social butterfly!"),
            Joke(214, "What do you call a seal that performs tricks?", "A navy seal!"),
            Joke(215, "Why are jellyfish bad employees?", "They're spineless!"),
            Joke(216, "What do you call a moose in a phone booth?", "Stuck!"),
            Joke(217, "Why did the swan go to the gym?", "To get buff!"),
            Joke(218, "What do you call a duck that robs banks?", "A safe quacker!"),
            Joke(219, "Why are sharks bad at basketball?", "They're afraid of nets!"),
            Joke(220, "What do you call a hippo in a garden?", "A hippo-pot-amus!"),
            Joke(221, "Why did the crane blush?", "It saw the bird bath!"),
            Joke(222, "What do you call a wolf in sheep's clothing?", "A wooligan!"),
            Joke(223, "Why don't eagles like fast food?", "They can't catch it!"),
            Joke(224, "What do you call a pig who tells jokes?", "A ham comedian!"),
            Joke(225, "Why did the flamingo stand on one leg?", "If it lifted both, it would fall!"),
            Joke(226, "What do you call a nervous insect?", "Jitterbug!"),
            Joke(227, "Why are rhinos so wrinkled?", "Have you tried ironing one?"),
            Joke(228, "What do you call a funny mountain goat?", "Hill-arious!"),
            Joke(229, "Why did the bat miss his turn?", "He was hanging around!"),
            Joke(230, "What do you call a dancing fish?", "A bass-anova!"),
            Joke(231, "Why don't anteaters ever get sick?", "They're full of ant-ibodies!"),
            Joke(232, "What do you call a baby eagle?", "A legal eagle!"),
            Joke(233, "Why did the otter cross the road?", "To get to the otter side!"),
            Joke(234, "What do you call a deer that costs a dollar?", "A buck!"),
            Joke(235, "Why are pelicans good businessmen?", "They know how to handle big bills!"),
            Joke(236, "What do you call a sheep that's always cold?", "A brrr-baa!"),
            Joke(237, "Why did the iguana go to the salon?", "To get a new reptile dysfunction!"),
            Joke(238, "What do you call a crab that plays baseball?", "A pinch hitter!"),
            Joke(239, "Why don't turtles play tennis?", "They're afraid of the net!"),
            Joke(240, "What do you call an ant that skips school?", "A truant!"),
            Joke(241, "Why did the peacock lose the poker game?", "He kept showing his hand!"),
            Joke(242, "What do you call a goose with money?", "A golden goose!"),
            Joke(243, "Why are dolphins bad at keeping time?", "They're always a little off-porpoise!"),
            Joke(244, "What do you call a hyena at a comedy club?", "The laughing stock!"),
            Joke(245, "Why did the toucan hide in the jungle?", "To toucan spy!"),
            Joke(246, "What do you call a donkey with three legs?", "A wonky donkey!"),
            Joke(247, "Why are platypuses so confused?", "They can't figure out what they are!"),
            Joke(248, "What do you call a buffalo with fancy clothes?", "Well-dressed!"),
            Joke(249, "Why did the ostrich bury its head?", "To mine for worms!"),
            Joke(250, "What do you call a sloth in a hurry?", "An oxymoron!"),
            
            // Work and Office Jokes (251-350)
            Joke(251, "Why did the scarecrow become a successful businessman?", "He was outstanding in his field!"),
            Joke(252, "What did the janitor say when he jumped out of the closet?", "Supplies!"),
            Joke(253, "Why did the employee get fired from the calendar factory?", "He took a day off!"),
            Joke(254, "What do you call a meeting that's been canceled?", "A relief!"),
            Joke(255, "Why did the accountant break up with the calculator?", "They weren't counting on each other!"),
            Joke(256, "What do you call a lazy person at work?", "A staff infection!"),
            Joke(257, "Why don't programmers like nature?", "It has too many bugs!"),
            Joke(258, "What did the boss say to the lazy employee?", "You're fired up for unemployment!"),
            Joke(259, "Why did the banker quit his job?", "He lost interest!"),
            Joke(260, "What do you call a coworker who's always tired?", "A deadline!"),
            Joke(261, "Why did the electrician close his shop?", "Business was too light!"),
            Joke(262, "What did the stapler say to the papers?", "I'm attached to you!"),
            Joke(263, "Why did the paperclip go to therapy?", "It had attachment issues!"),
            Joke(264, "What do you call an office with no coffee?", "A depresso place!"),
            Joke(265, "Why did the printer go to jail?", "It kept jamming!"),
            Joke(266, "What did the pencil say to the paper?", "I dot my i's on you!"),
            Joke(267, "Why did the clock get promoted?", "It was ahead of its time!"),
            Joke(268, "What do you call a meeting with no agenda?", "A chat!"),
            Joke(269, "Why did the filing cabinet feel proud?", "It had everything sorted out!"),
            Joke(270, "What did the laptop say to the dentist?", "My Bluetooth hurts!"),
            Joke(271, "Why did the spreadsheet go to therapy?", "It had too many cells!"),
            Joke(272, "What do you call an email that's always late?", "Snail mail!"),
            Joke(273, "Why did the highlighter feel special?", "Everything it did was brilliant!"),
            Joke(274, "What did the desk say to the chair?", "I've got your back!"),
            Joke(275, "Why did the calendar feel dated?", "It was stuck in the past!"),
            Joke(276, "What do you call a successful elevator?", "A raise!"),
            Joke(277, "Why did the rubber band get promoted?", "It was very flexible!"),
            Joke(278, "What did the coffee say during the meeting?", "I'm just here to get buzzed!"),
            Joke(279, "Why did the notebook feel important?", "Everyone took notes of it!"),
            Joke(280, "What do you call a stressed keyboard?", "Typing under pressure!"),
            Joke(281, "Why did the scanner feel unappreciated?", "It was always overlooked!"),
            Joke(282, "What did the monitor say to the computer?", "I've got my eye on you!"),
            Joke(283, "Why did the mouse get fired?", "It kept clicking around!"),
            Joke(284, "What do you call a pen that won't write?", "Pointless!"),
            Joke(285, "Why did the sticky note feel important?", "It was always getting noticed!"),
            Joke(286, "What did the trash can say to the paper?", "You're garbage to me!"),
            Joke(287, "Why did the whiteboard feel smart?", "It was remarkable!"),
            Joke(288, "What do you call an office plant that talks?", "A palm reader!"),
            Joke(289, "Why did the scissors feel cut off?", "It wasn't included in the meeting!"),
            Joke(290, "What did the envelope say to the stamp?", "Stick with me!"),
            Joke(291, "Why did the copier feel depressed?", "It was just making copies!"),
            Joke(292, "What do you call a calculator that's always wrong?", "Mis-calculated!"),
            Joke(293, "Why did the inbox feel overwhelmed?", "Too much mail drama!"),
            Joke(294, "What did the Wi-Fi say to the devices?", "Stay connected!"),
            Joke(295, "Why did the charger feel powerful?", "It was energizing!"),
            Joke(296, "What do you call a boring presentation?", "A power nap!"),
            Joke(297, "Why did the extension cord feel extended?", "It was stretching the truth!"),
            Joke(298, "What did the keyboard say to the typo?", "You're not my type!"),
            Joke(299, "Why did the document feel shredded?", "It went through a lot!"),
            Joke(300, "What do you call a happy fax machine?", "Fax-tastic!"),
            Joke(301, "Why did the projector feel bright?", "It was always in the spotlight!"),
            Joke(302, "What did the server say during the crash?", "I need a break!"),
            Joke(303, "Why did the password feel secure?", "It had special characters!"),
            Joke(304, "What do you call a confused browser?", "Internet Explored!"),
            Joke(305, "Why did the folder feel organized?", "Everything was filed correctly!"),
            Joke(306, "What did the router say to the modem?", "Let's stay connected!"),
            Joke(307, "Why did the backup drive feel relieved?", "It had everyone's back!"),
            Joke(308, "What do you call a Monday morning meeting?", "Painful!"),
            Joke(309, "Why did the desk lamp feel bright?", "It was enlightening!"),
            Joke(310, "What did the deadline say to the project?", "I'm coming for you!"),
            Joke(311, "Why did the email feel unread?", "It was ignored!"),
            Joke(312, "What do you call an empty conference room?", "A dream!"),
            Joke(313, "Why did the intern feel used?", "Everyone needed coffee!"),
            Joke(314, "What did the vacation day say?", "Take me now!"),
            Joke(315, "Why did the report feel long?", "It had too many pages!"),
            Joke(316, "What do you call a happy HR person?", "A myth!"),
            Joke(317, "Why did the budget feel tight?", "No room to breathe!"),
            Joke(318, "What did the paycheck say?", "You earned me!"),
            Joke(319, "Why did the lunch break feel short?", "Time flies when eating!"),
            Joke(320, "What do you call a productive Friday?", "Rare!"),
            Joke(321, "Why did the ergonomic chair feel supportive?", "It had everyone's back!"),
            Joke(322, "What did the overtime say?", "I'm extra!"),
            Joke(323, "Why did the team building feel awkward?", "Forced fun!"),
            Joke(324, "What do you call a silent office?", "Suspicious!"),
            Joke(325, "Why did the dress code feel strict?", "No casual Fridays!"),
            Joke(326, "What did the performance review say?", "Room for improvement!"),
            Joke(327, "Why did the corner office feel prestigious?", "It had the best view!"),
            Joke(328, "What do you call a long commute?", "Punishment!"),
            Joke(329, "Why did the break room feel popular?", "Free snacks!"),
            Joke(330, "What did the parking spot say?", "I'm taken!"),
            Joke(331, "Why did the elevator feel awkward?", "Silence with strangers!"),
            Joke(332, "What do you call a noisy coworker?", "The office DJ!"),
            Joke(333, "Why did the water cooler feel social?", "All the gossip!"),
            Joke(334, "What did the microwave say?", "I'm on fire!"),
            Joke(335, "Why did the vending machine feel rejected?", "Wrong change!"),
            Joke(336, "What do you call a helpful IT person?", "A unicorn!"),
            Joke(337, "Why did the fire drill feel necessary?", "Safety first!"),
            Joke(338, "What did the suggestion box say?", "I'm empty inside!"),
            Joke(339, "Why did the name badge feel important?", "Identity matters!"),
            Joke(340, "What do you call a cluttered desk?", "Organized chaos!"),
            Joke(341, "Why did the office party feel mandatory?", "Fun required!"),
            Joke(342, "What did the birthday card say?", "Sign here for cake!"),
            Joke(343, "Why did the potluck feel risky?", "Mystery dishes!"),
            Joke(344, "What do you call a quiet bathroom?", "Peace!"),
            Joke(345, "Why did the hand sanitizer feel popular?", "Germ-free hugs!"),
            Joke(346, "What did the recycling bin say?", "Give me another chance!"),
            Joke(347, "Why did the security badge feel powerful?", "Access granted!"),
            Joke(348, "What do you call a lost USB drive?", "Panic!"),
            Joke(349, "Why did the headphones feel peaceful?", "No interruptions!"),
            Joke(350, "What did the office supply closet say?", "Take what you need!"),
            
            // Science and Tech Jokes (351-450)
            Joke(351, "Why did the physicist break up with the biologist?", "There was no chemistry!"),
            Joke(352, "What did the computer do at lunchtime?", "Had a byte!"),
            Joke(353, "Why are chemists great at solving problems?", "They have all the solutions!"),
            Joke(354, "What do you call a computer that sings?", "A-Dell!"),
            Joke(355, "Why did the robot go on a diet?", "It had too many bytes!"),
            Joke(356, "What did the biologist wear to impress?", "Designer genes!"),
            Joke(357, "Why don't scientists trust stairs?", "They're always up to something!"),
            Joke(358, "What do you call a snake that's 3.14 meters long?", "A pi-thon!"),
            Joke(359, "Why did the photon check no luggage?", "It was traveling light!"),
            Joke(360, "What do computers snack on?", "Microchips!"),
            Joke(361, "Why did the cell phone go to school?", "It wanted to be a smart phone!"),
            Joke(362, "What did the DNA say to the other DNA?", "Do these genes make me look fat?"),
            Joke(363, "Why was the math book depressed?", "It had too many problems!"),
            Joke(364, "What do you call a belt made of watches?", "A waist of time!"),
            Joke(365, "Why did the atom go to jail?", "For breaking the law!"),
            Joke(366, "What did the chemist say when he found two isotopes of helium?", "HeHe!"),
            Joke(367, "Why don't programmers like to go outside?", "The sun causes too much glare on their screens!"),
            Joke(368, "What do you call a fake noodle in a chemistry lab?", "An impasta!"),
            Joke(369, "Why did the electron refuse to fight the proton?", "It didn't want to be negative!"),
            Joke(370, "What do you call a fish made of two sodium atoms?", "2 Na!"),
            Joke(371, "Why did the computer catch a cold?", "It left its Windows open!"),
            Joke(372, "What did the battery say to the chip?", "I'm positive we'll work together!"),
            Joke(373, "Why are programming languages so strict?", "They won't accept your excuses!"),
            Joke(374, "What do you call a database administrator's favorite music?", "SQL and Blues!"),
            Joke(375, "Why did the software developer quit his job?", "He didn't get arrays!"),
            Joke(376, "What did the Java say to the C?", "You have no class!"),
            Joke(377, "Why don't bachelors like Git?", "Because they have commitment issues!"),
            Joke(378, "What do you call a programming language that complains?", "Perl of complaints!"),
            Joke(379, "Why did the programmer use the dark theme?", "Because light attracts bugs!"),
            Joke(380, "What did HTML say to CSS?", "You're so stylish!"),
            Joke(381, "Why did JavaScript go to therapy?", "It had too many issues!"),
            Joke(382, "What do you call a dinosaur that knows HTML?", "A T-REX-t!"),
            Joke(383, "Why did the API break up with the database?", "It wasn't getting any responses!"),
            Joke(384, "What did the server say to the request?", "I'm processing your feelings!"),
            Joke(385, "Why did the variable feel undefined?", "It hadn't found its value!"),
            Joke(386, "What do you call a loop that never ends?", "A wedding ring!"),
            Joke(387, "Why did the function feel called out?", "It was being invoked!"),
            Joke(388, "What did the boolean say?", "It's true, I'm positive!"),
            Joke(389, "Why did the array start at zero?", "It was index-perienced!"),
            Joke(390, "What do you call a recursive joke?", "What do you call a recursive joke?"),
            Joke(391, "Why did the quantum physicist break up with the astronomer?", "They needed space!"),
            Joke(392, "What did the black hole say?", "I'm so attractive!"),
            Joke(393, "Why did the neutrino go to the party alone?", "It barely interacts!"),
            Joke(394, "What do you call a lazy quantum particle?", "A rest mass!"),
            Joke(395, "Why did the proton stay positive?", "It was in its nature!"),
            Joke(396, "What did the neutron say to the proton?", "I'm neutral about you!"),
            Joke(397, "Why did the quark feel strange?", "It was its flavor!"),
            Joke(398, "What do you call a lazy element?", "Nobelium!"),
            Joke(399, "Why did oxygen go on a date with potassium?", "It was OK!"),
            Joke(400, "What did the thermometer say to the graduated cylinder?", "You may have graduated, but I have more degrees!"),
            Joke(401, "Why did the geologist break up with their partner?", "They took them for granite!"),
            Joke(402, "What do you call a rock that never goes to school?", "A skite!"),
            Joke(403, "Why did the tectonic plate feel misunderstood?", "It was under a lot of pressure!"),
            Joke(404, "What did the volcano say?", "I lava you!"),
            Joke(405, "Why did the fossil feel old?", "It was past its prime!"),
            Joke(406, "What do you call a mineral that's always gossiping?", "A talc-er!"),
            Joke(407, "Why did the sediment feel settled?", "It hit rock bottom!"),
            Joke(408, "What did the earthquake say to the building?", "I'll shake things up!"),
            Joke(409, "Why did the crystal feel clear?", "It was transparent!"),
            Joke(410, "What do you call a nervous geologist?", "Shaky!"),
            Joke(411, "Why did the astronaut break up with Earth?", "They needed more space!"),
            Joke(412, "What did the sun say to the moon?", "You're just going through a phase!"),
            Joke(413, "Why did the comet feel lonely?", "It was always passing by!"),
            Joke(414, "What do you call a sad meteor?", "A crying star!"),
            Joke(415, "Why did the asteroid feel down?", "It was hitting rock bottom!"),
            Joke(416, "What did the galaxy say?", "I'm starstruck!"),
            Joke(417, "Why did the satellite feel watched?", "It was always orbiting!"),
            Joke(418, "What do you call a tired star?", "A dwarf star!"),
            Joke(419, "Why did the planet feel gassy?", "It was Jupiter!"),
            Joke(420, "What did the rocket say?", "I'm just trying to launch my career!"),
            Joke(421, "Why did the mathematician refuse to eat pi?", "It went on forever!"),
            Joke(422, "What did the zero say to the eight?", "Nice belt!"),
            Joke(423, "Why did the obtuse angle go to the beach?", "Because it was over 90 degrees!"),
            Joke(424, "What do you call a number that can't keep still?", "A roamin' numeral!"),
            Joke(425, "Why did the fraction feel insecure?", "It was less than whole!"),
            Joke(426, "What did the triangle say to the circle?", "You're pointless!"),
            Joke(427, "Why did the student do multiplication on the floor?", "The teacher told them not to use tables!"),
            Joke(428, "What do you call a hen that counts eggs?", "A mathema-chicken!"),
            Joke(429, "Why did the polynomial plant wilt?", "It had square roots!"),
            Joke(430, "What did the calculator say to the math student?", "You can count on me!"),
            Joke(431, "Why did the equal sign feel humble?", "It wasn't greater or less than anyone!"),
            Joke(432, "What do you call a mathematical bird?", "A poly-gon!"),
            Joke(433, "Why did the plus sign feel positive?", "It added value!"),
            Joke(434, "What did the minus say?", "I'm feeling negative!"),
            Joke(435, "Why did the decimal feel small?", "It was just a point!"),
            Joke(436, "What do you call a mathematical snake?", "A pi-thon!"),
            Joke(437, "Why did the geometry teacher feel shapely?", "They knew all the angles!"),
            Joke(438, "What did the algebra book say?", "I've got my own problems!"),
            Joke(439, "Why did the statistician drown?", "The river was 3 feet deep on average!"),
            Joke(440, "What do you call a number that's friends with everyone?", "A social integer!"),
            Joke(441, "Why did the prime number feel lonely?", "It was indivisible!"),
            Joke(442, "What did the exponent say?", "I'm raising to the occasion!"),
            Joke(443, "Why did the parallel lines feel sad?", "They would never meet!"),
            Joke(444, "What do you call a math teacher who hates fractions?", "Someone who can't handle the whole truth!"),
            Joke(445, "Why did the tangent break up with the sine?", "It was going off on a tangent!"),
            Joke(446, "What did the logarithm say?", "I'm just trying to find my base!"),
            Joke(447, "Why did the integral feel complete?", "It had all the areas covered!"),
            Joke(448, "What do you call a paranoid mathematician?", "Someone who thinks people are plotting against them!"),
            Joke(449, "Why did the mathematician get cold?", "They were standing in degrees!"),
            Joke(450, "What did the function say to the variable?", "I'm dependent on you!"),
            
            // Sports and Games Jokes (451-550)
            Joke(451, "Why did the golfer bring two pairs of pants?", "In case he got a hole in one!"),
            Joke(452, "What do you call a pig that plays basketball?", "A ball hog!"),
            Joke(453, "Why did the soccer ball go to the bank?", "To get its quarterback!"),
            Joke(454, "What do you call a boomerang that doesn't come back?", "A stick!"),
            Joke(455, "Why did the football coach go to the bank?", "To get his quarter back!"),
            Joke(456, "What do you call a fish that plays tennis?", "A volley fish!"),
            Joke(457, "Why did the baseball player bring a ladder?", "He wanted to hit a home run!"),
            Joke(458, "What do you call a dinosaur that plays cricket?", "A Tyrannosaurus Flex!"),
            Joke(459, "Why did the chess piece go to therapy?", "It had too many moves!"),
            Joke(460, "What do you call a lazy sports reporter?", "A bench warmer!"),
            Joke(461, "Why did the basketball player bring a suitcase?", "He was traveling!"),
            Joke(462, "What do you call a dog that plays football?", "A golden receiver!"),
            Joke(463, "Why did the hockey player go to jail?", "For checking too hard!"),
            Joke(464, "What do you call a tennis player who always serves?", "A waiter!"),
            Joke(465, "Why did the boxer bring a pencil to the ring?", "To draw blood!"),
            Joke(466, "What do you call a swimmer who's always complaining?", "A whine-stroke!"),
            Joke(467, "Why did the runner stop in the middle of the race?", "He was running out of steam!"),
            Joke(468, "What do you call a bowling ball that's also a detective?", "Sherlock Rolls!"),
            Joke(469, "Why did the volleyball player bring a ladder?", "For the high sets!"),
            Joke(470, "What do you call a skier who tells jokes?", "A ski-median!"),
            Joke(471, "Why did the weightlifter break up with the treadmill?", "It was running away from their problems!"),
            Joke(472, "What do you call a golfer who's also a gardener?", "A tee planter!"),
            Joke(473, "Why did the archer feel bow-led over?", "He hit the target!"),
            Joke(474, "What do you call a cyclist who's always tired?", "Two-tired!"),
            Joke(475, "Why did the diver bring an umbrella?", "In case of a splash!"),
            Joke(476, "What do you call a gymnast who's always late?", "A behind-the-balance-beam!"),
            Joke(477, "Why did the fencer feel pointed out?", "They were always making a point!"),
            Joke(478, "What do you call a kayaker who's always calm?", "Going with the flow!"),
            Joke(479, "Why did the marathon runner feel accomplished?", "They went the distance!"),
            Joke(480, "What do you call a surfer who's always happy?", "Wave-ing good vibes!"),
            Joke(481, "Why did the poker player fold?", "He couldn't deal with the pressure!"),
            Joke(482, "What do you call a chess player who's always honest?", "A straight knight!"),
            Joke(483, "Why did the card game feel shuffled?", "Things were getting mixed up!"),
            Joke(484, "What do you call a dice that's always lucky?", "On a roll!"),
            Joke(485, "Why did the board game feel bored?", "No one wanted to play!"),
            Joke(486, "What do you call a video game character who's always running?", "A marathoner!"),
            Joke(487, "Why did the puzzle feel accomplished?", "All the pieces came together!"),
            Joke(488, "What do you call a trivia player who knows everything?", "A quiz-ard!"),
            Joke(489, "Why did the bingo player feel lucky?", "Their number came up!"),
            Joke(490, "What do you call a pool player who never loses?", "A cue-master!"),
            Joke(491, "Why did the dart player feel pointed?", "They were always on target!"),
            Joke(492, "What do you call a Monopoly player who's always buying?", "A property hoarder!"),
            Joke(493, "Why did the Scrabble player feel wordy?", "They had all the letters!"),
            Joke(494, "What do you call a Jenga player who's nervous?", "Shaky!"),
            Joke(495, "Why did the dominoes feel influential?", "They had a chain reaction!"),
            Joke(496, "What do you call a crossword puzzle that's half done?", "Work in progress!"),
            Joke(497, "Why did the Rubik's cube feel twisted?", "Everything was mixed up!"),
            Joke(498, "What do you call a yo-yo that's really good?", "Up and coming!"),
            Joke(499, "Why did the frisbee feel thrown off?", "It was discus-sed!"),
            Joke(500, "What do you call a hula hoop champion?", "Well-rounded!"),
            Joke(501, "Why did the referee feel watched?", "All eyes were on them!"),
            Joke(502, "What do you call a coach who's always yelling?", "Loud and proud!"),
            Joke(503, "Why did the trophy feel shiny?", "It was polished!"),
            Joke(504, "What do you call a scoreboard that's broken?", "Point-less!"),
            Joke(505, "Why did the stadium feel empty?", "No fans!"),
            Joke(506, "What do you call a jersey that's too small?", "Tight end!"),
            Joke(507, "Why did the sports car feel fast?", "It was in the passing lane!"),
            Joke(508, "What do you call a mascot who's always dancing?", "The team spirit!"),
            Joke(509, "Why did the fan feel dedicated?", "They never missed a game!"),
            Joke(510, "What do you call a sports announcer who whispers?", "A quiet commentator!"),
            Joke(511, "Why did the locker room smell?", "Too many athletes!"),
            Joke(512, "What do you call a sports drink that's flat?", "De-energized!"),
            Joke(513, "Why did the medal feel heavy?", "It was golden!"),
            Joke(514, "What do you call a podium for three?", "The top spots!"),
            Joke(515, "Why did the starting gun feel nervous?", "It was about to go off!"),
            Joke(516, "What do you call a finish line that moves?", "Unreachable goals!"),
            Joke(517, "Why did the stopwatch feel precise?", "Every second counted!"),
            Joke(518, "What do you call a sports injury that heals fast?", "A quick recovery!"),
            Joke(519, "Why did the training feel tough?", "No pain, no gain!"),
            Joke(520, "What do you call a warm-up that's cold?", "Cool down!"),
            Joke(521, "Why did the stretching feel relaxing?", "It was flexible!"),
            Joke(522, "What do you call a sports bet that pays off?", "A winning ticket!"),
            Joke(523, "Why did the home team feel advantaged?", "Home field!"),
            Joke(524, "What do you call a visiting team that wins?", "Road warriors!"),
            Joke(525, "Why did the overtime feel exhausting?", "Extra effort!"),
            Joke(526, "What do you call a tie game?", "Evenly matched!"),
            Joke(527, "Why did the playoffs feel intense?", "Win or go home!"),
            Joke(528, "What do you call a championship that's close?", "A nail-biter!"),
            Joke(529, "Why did the dynasty feel powerful?", "Multiple wins!"),
            Joke(530, "What do you call an underdog that wins?", "A Cinderella story!"),
            Joke(531, "Why did the comeback feel exciting?", "Never give up!"),
            Joke(532, "What do you call a blowout game?", "Not close!"),
            Joke(533, "Why did the shutout feel complete?", "Zero points allowed!"),
            Joke(534, "What do you call a perfect game?", "Flawless!"),
            Joke(535, "Why did the record feel broken?", "New achievement!"),
            Joke(536, "What do you call an MVP?", "The most valuable!"),
            Joke(537, "Why did the rookie feel new?", "First season!"),
            Joke(538, "What do you call a veteran player?", "Experienced!"),
            Joke(539, "Why did the hall of fame feel prestigious?", "Only the best!"),
            Joke(540, "What do you call a retired jersey?", "Honored!"),
            Joke(541, "Why did the draft pick feel chosen?", "They were selected!"),
            Joke(542, "What do you call a free agent?", "Available!"),
            Joke(543, "Why did the trade feel surprising?", "Unexpected move!"),
            Joke(544, "What do you call a contract extension?", "More years!"),
            Joke(545, "Why did the signing bonus feel generous?", "Extra money!"),
            Joke(546, "What do you call a salary cap?", "Spending limit!"),
            Joke(547, "Why did the buyout feel final?", "End of contract!"),
            Joke(548, "What do you call a waiver wire?", "Second chances!"),
            Joke(549, "Why did the minor leagues feel hopeful?", "Path to the top!"),
            Joke(550, "What do you call the big leagues?", "The show!"),
            
            // Family and Kids Jokes (551-650)
            Joke(551, "Why did the kid bring a ladder to school?", "To go to high school!"),
            Joke(552, "What do you call a bear that's also a dad?", "A papa bear!"),
            Joke(553, "Why did the baby cookie cry?", "Because its mama was a wafer so long!"),
            Joke(554, "What do you call a sleeping baby?", "A dream come true!"),
            Joke(555, "Why did the parent feel tired?", "Kids don't come with manuals!"),
            Joke(556, "What do you call a grandmother who tells jokes?", "A grand-comedian!"),
            Joke(557, "Why did the grandfather clock feel old?", "It was ticking for years!"),
            Joke(558, "What do you call a sibling who borrows everything?", "A share-ling!"),
            Joke(559, "Why did the twin feel like a copy?", "They looked identical!"),
            Joke(560, "What do you call a cousin who visits often?", "A frequent relative!"),
            Joke(561, "Why did the aunt feel fancy?", "She was always dressed up!"),
            Joke(562, "What do you call an uncle who tells stories?", "A tale-bearer!"),
            Joke(563, "Why did the nephew feel young?", "He was still growing!"),
            Joke(564, "What do you call a niece who dances?", "A little performer!"),
            Joke(565, "Why did the family tree feel branched out?", "So many relatives!"),
            Joke(566, "What do you call a family reunion that's loud?", "Typical!"),
            Joke(567, "Why did the potluck feel full?", "Everyone brought dishes!"),
            Joke(568, "What do you call holiday stress?", "Family fun!"),
            Joke(569, "Why did the photo album feel nostalgic?", "So many memories!"),
            Joke(570, "What do you call a family game night?", "Competitive bonding!"),
            Joke(571, "Why did the bedtime story feel sleepy?", "It was time for dreams!"),
            Joke(572, "What do you call a lullaby that works?", "Sleep magic!"),
            Joke(573, "Why did the stuffed animal feel loved?", "Always hugged!"),
            Joke(574, "What do you call a nightlight?", "Fear fighter!"),
            Joke(575, "Why did the monster under the bed feel lonely?", "No one visited!"),
            Joke(576, "What do you call a tooth under a pillow?", "Fairy bait!"),
            Joke(577, "Why did the sandbox feel gritty?", "Too much sand!"),
            Joke(578, "What do you call a swing that goes high?", "Cloud chaser!"),
            Joke(579, "Why did the slide feel slippery?", "That's the point!"),
            Joke(580, "What do you call a seesaw that's balanced?", "Rare!"),
            Joke(581, "Why did the merry-go-round feel dizzy?", "Too many spins!"),
            Joke(582, "What do you call a jungle gym climber?", "A little monkey!"),
            Joke(583, "Why did the bubble feel fragile?", "Pop goes the bubble!"),
            Joke(584, "What do you call sidewalk chalk art?", "Temporary masterpiece!"),
            Joke(585, "Why did the jump rope feel skippy?", "Hop, hop, hop!"),
            Joke(586, "What do you call hide and seek champion?", "Never found!"),
            Joke(587, "Why did the tag game feel it?", "Always running!"),
            Joke(588, "What do you call a pillow fight winner?", "Fluffy champion!"),
            Joke(589, "Why did the blanket fort feel cozy?", "Perfect hideout!"),
            Joke(590, "What do you call a cardboard box?", "Imagination station!"),
            Joke(591, "Why did the coloring book feel artistic?", "So many colors!"),
            Joke(592, "What do you call a crayon that's broken?", "Still works!"),
            Joke(593, "Why did the finger paint feel messy?", "Art is messy!"),
            Joke(594, "What do you call a macaroni necklace?", "Fine dining jewelry!"),
            Joke(595, "Why did the glitter feel sparkly?", "Never goes away!"),
            Joke(596, "What do you call a sticker collection?", "Sticky treasure!"),
            Joke(597, "Why did the play-dough feel squishy?", "Moldable fun!"),
            Joke(598, "What do you call a paper airplane?", "Desk to floor express!"),
            Joke(599, "Why did the puppet feel handy?", "Always on hand!"),
            Joke(600, "What do you call a magic trick for kids?", "Mind blown!"),
            Joke(601, "Why did the bicycle feel wheely good?", "Two-wheeled freedom!"),
            Joke(602, "What do you call training wheels?", "Balance beginners!"),
            Joke(603, "Why did the scooter feel pushed?", "Kick, kick, glide!"),
            Joke(604, "What do you call a skateboard trick?", "Ground flying!"),
            Joke(605, "Why did the roller skates feel groovy?", "Rolling in style!"),
            Joke(606, "What do you call a pogo stick?", "Bounce machine!"),
            Joke(607, "Why did the kite feel high?", "Wind rider!"),
            Joke(608, "What do you call a water balloon?", "Splash grenade!"),
            Joke(609, "Why did the sprinkler feel refreshing?", "Summer essential!"),
            Joke(610, "What do you call a slip and slide?", "Wet and wild!"),
            Joke(611, "Why did the pool floaty feel relaxed?", "Just floating along!"),
            Joke(612, "What do you call a beach bucket?", "Sand castle starter kit!"),
            Joke(613, "Why did the ice cream truck feel magical?", "Music means treats!"),
            Joke(614, "What do you call a popsicle on a hot day?", "Brain freeze incoming!"),
            Joke(615, "Why did the lemonade stand feel entrepreneurial?", "First business!"),
            Joke(616, "What do you call a treehouse?", "Sky home!"),
            Joke(617, "Why did the campfire feel toasty?", "S'mores time!"),
            Joke(618, "What do you call a firefly jar?", "Nightlight in a bottle!"),
            Joke(619, "Why did the sleeping bag feel snug?", "Burrito style!"),
            Joke(620, "What do you call a flashlight at night?", "Darkness defeater!"),
            Joke(621, "Why did the school bus feel yellow?", "Safety color!"),
            Joke(622, "What do you call a backpack that's heavy?", "Homework holder!"),
            Joke(623, "Why did the lunch box feel packed?", "Full of goodies!"),
            Joke(624, "What do you call a juice box?", "Sippy happiness!"),
            Joke(625, "Why did the apple for teacher feel traditional?", "Old school cool!"),
            Joke(626, "What do you call a gold star?", "Good job proof!"),
            Joke(627, "Why did the report card feel graded?", "Effort measured!"),
            Joke(628, "What do you call a permission slip?", "Field trip ticket!"),
            Joke(629, "Why did the field trip feel exciting?", "Learning adventure!"),
            Joke(630, "What do you call a science fair project?", "Last minute miracle!"),
            Joke(631, "Why did the spelling bee feel wordy?", "Letter perfect!"),
            Joke(632, "What do you call a show and tell item?", "Bragging rights!"),
            Joke(633, "Why did the recess feel short?", "Fun flies!"),
            Joke(634, "What do you call a snow day?", "Pajama victory!"),
            Joke(635, "Why did the homework feel endless?", "More and more!"),
            Joke(636, "What do you call a birthday party invitation?", "Fun guarantee!"),
            Joke(637, "Why did the pinata feel hit?", "Candy explosion!"),
            Joke(638, "What do you call musical chairs?", "Sit or lose!"),
            Joke(639, "Why did the birthday cake feel old?", "More candles!"),
            Joke(640, "What do you call a goodie bag?", "Party treasure!"),
            Joke(641, "Why did the present feel wrapped?", "Surprise inside!"),
            Joke(642, "What do you call a thank you card?", "Gratitude note!"),
            Joke(643, "Why did the party hat feel festive?", "Cone of celebration!"),
            Joke(644, "What do you call party streamers?", "Decoration confetti!"),
            Joke(645, "Why did the balloon animal feel twisted?", "Artistic squeak!"),
            Joke(646, "What do you call a face painter?", "Temporary tattoo artist!"),
            Joke(647, "Why did the bounce house feel bouncy?", "Jump central!"),
            Joke(648, "What do you call a clown at a party?", "Funny business!"),
            Joke(649, "Why did the magic show feel amazing?", "Illusion confusion!"),
            Joke(650, "What do you call a sleepover?", "No sleep party!"),
            
            // Travel and Places Jokes (651-750)
            Joke(651, "Why did the tourist bring a ladder?", "To see the high points!"),
            Joke(652, "What do you call a suitcase that's too heavy?", "Over packed!"),
            Joke(653, "Why did the passport feel stamped?", "So many countries!"),
            Joke(654, "What do you call a plane that's late?", "Delayed departure!"),
            Joke(655, "Why did the airport feel terminal?", "Gate after gate!"),
            Joke(656, "What do you call a long flight?", "Sky time!"),
            Joke(657, "Why did the jetlag feel tired?", "Time zone confusion!"),
            Joke(658, "What do you call a window seat?", "Cloud viewing!"),
            Joke(659, "Why did the aisle seat feel bumped?", "Cart traffic!"),
            Joke(660, "What do you call airplane food?", "Sky mystery!"),
            Joke(661, "Why did the hotel feel booked?", "No vacancy!"),
            Joke(662, "What do you call room service?", "Lazy luxury!"),
            Joke(663, "Why did the minibar feel expensive?", "Tiny prices, big cost!"),
            Joke(664, "What do you call a hotel pool?", "Vacation essential!"),
            Joke(665, "Why did the continental breakfast feel free?", "Included delight!"),
            Joke(666, "What do you call a tour guide?", "Walking Wikipedia!"),
            Joke(667, "Why did the souvenir shop feel touristy?", "Magnets everywhere!"),
            Joke(668, "What do you call a postcard?", "Wish you were here!"),
            Joke(669, "Why did the camera feel clicked?", "Memory capturing!"),
            Joke(670, "What do you call a selfie stick?", "Arm extension!"),
            Joke(671, "Why did Paris feel romantic?", "City of love!"),
            Joke(672, "What do you call the Eiffel Tower?", "Iron elegance!"),
            Joke(673, "Why did London feel royal?", "Crown jewel city!"),
            Joke(674, "What do you call Big Ben?", "Time keeper!"),
            Joke(675, "Why did Rome feel ancient?", "So much history!"),
            Joke(676, "What do you call the Colosseum?", "Gladiator venue!"),
            Joke(677, "Why did Tokyo feel futuristic?", "High-tech wonderland!"),
            Joke(678, "What do you call sushi in Japan?", "Fresh fish!"),
            Joke(679, "Why did New York feel busy?", "City that never sleeps!"),
            Joke(680, "What do you call Times Square?", "Bright lights central!"),
            Joke(681, "Why did Los Angeles feel sunny?", "California dreams!"),
            Joke(682, "What do you call Hollywood?", "Star factory!"),
            Joke(683, "Why did Las Vegas feel lucky?", "Jackpot city!"),
            Joke(684, "What do you call the Grand Canyon?", "Big hole!"),
            Joke(685, "Why did Florida feel hot?", "Sunshine state!"),
            Joke(686, "What do you call Disney World?", "Happiest place!"),
            Joke(687, "Why did Hawaii feel tropical?", "Island paradise!"),
            Joke(688, "What do you call a luau?", "Beach party!"),
            Joke(689, "Why did Alaska feel cold?", "Frozen frontier!"),
            Joke(690, "What do you call Northern Lights?", "Sky magic!"),
            Joke(691, "Why did the beach feel sandy?", "Obvious observation!"),
            Joke(692, "What do you call ocean waves?", "Nature's rhythm!"),
            Joke(693, "Why did the mountain feel tall?", "Peak achievement!"),
            Joke(694, "What do you call a hiking trail?", "Nature's gym!"),
            Joke(695, "Why did the waterfall feel wet?", "Splashy beauty!"),
            Joke(696, "What do you call a national park?", "Protected wilderness!"),
            Joke(697, "Why did the desert feel dry?", "Sand for days!"),
            Joke(698, "What do you call an oasis?", "Desert surprise!"),
            Joke(699, "Why did the rainforest feel humid?", "Jungle moisture!"),
            Joke(700, "What do you call exotic animals?", "Safari sightings!"),
            Joke(701, "Why did the cruise ship feel floating?", "Ocean hotel!"),
            Joke(702, "What do you call seasickness?", "Waves of regret!"),
            Joke(703, "Why did the train feel on track?", "Rail riding!"),
            Joke(704, "What do you call a scenic route?", "Long but pretty!"),
            Joke(705, "Why did the road trip feel long?", "Are we there yet?"),
            Joke(706, "What do you call rest stops?", "Bathroom breaks!"),
            Joke(707, "Why did the GPS feel bossy?", "Recalculating!"),
            Joke(708, "What do you call a wrong turn?", "Adventure detour!"),
            Joke(709, "Why did the flat tire feel deflated?", "Road trouble!"),
            Joke(710, "What do you call car games?", "Time killers!"),
            Joke(711, "Why did the camping trip feel outdoorsy?", "Nature calling!"),
            Joke(712, "What do you call a tent?", "Outdoor bedroom!"),
            Joke(713, "Why did the campfire feel warm?", "Fireside stories!"),
            Joke(714, "What do you call stargazing?", "Night sky theater!"),
            Joke(715, "Why did the RV feel mobile?", "Home on wheels!"),
            Joke(716, "What do you call glamping?", "Fancy camping!"),
            Joke(717, "Why did the backpacking trip feel heavy?", "Everything on back!"),
            Joke(718, "What do you call a hostel?", "Budget beds!"),
            Joke(719, "Why did the vacation feel needed?", "Burnout relief!"),
            Joke(720, "What do you call work emails on vacation?", "Boundary violations!"),
            Joke(721, "Why did the staycation feel cheap?", "Home vacation!"),
            Joke(722, "What do you call a day trip?", "Quick escape!"),
            Joke(723, "Why did the getaway feel relaxing?", "Stress relief!"),
            Joke(724, "What do you call a honeymoon?", "Love trip!"),
            Joke(725, "Why did the anniversary trip feel special?", "Milestone memories!"),
            Joke(726, "What do you call a family vacation?", "Organized chaos!"),
            Joke(727, "Why did the solo trip feel independent?", "Me time!"),
            Joke(728, "What do you call a group tour?", "Herding tourists!"),
            Joke(729, "Why did the adventure travel feel exciting?", "Thrill seeking!"),
            Joke(730, "What do you call a relaxing vacation?", "Do nothing trip!"),
            Joke(731, "Why did the cultural trip feel educational?", "Learning journey!"),
            Joke(732, "What do you call a food tour?", "Eating adventure!"),
            Joke(733, "Why did the wine tour feel tipsy?", "Grape exploration!"),
            Joke(734, "What do you call a shopping trip?", "Wallet workout!"),
            Joke(735, "Why did the spa vacation feel pampered?", "Self-care retreat!"),
            Joke(736, "What do you call a ski trip?", "Snow adventure!"),
            Joke(737, "Why did the beach vacation feel sunny?", "Sand and surf!"),
            Joke(738, "What do you call a city break?", "Urban exploration!"),
            Joke(739, "Why did the countryside trip feel peaceful?", "Rural relaxation!"),
            Joke(740, "What do you call an island getaway?", "Tropical escape!"),
            Joke(741, "Why did the river cruise feel flowing?", "Waterway wandering!"),
            Joke(742, "What do you call a lake house?", "Water retreat!"),
            Joke(743, "Why did the cabin feel cozy?", "Woods comfort!"),
            Joke(744, "What do you call a resort?", "All-inclusive ease!"),
            Joke(745, "Why did the bed and breakfast feel charming?", "Homey hospitality!"),
            Joke(746, "What do you call a vacation rental?", "Temporary home!"),
            Joke(747, "Why did the time share feel complicated?", "Shared ownership!"),
            Joke(748, "What do you call travel insurance?", "Just in case!"),
            Joke(749, "Why did the delayed flight feel frustrating?", "Waiting game!"),
            Joke(750, "What do you call lost luggage?", "Airline mystery!"),
            
            // Music and Entertainment Jokes (751-850)
            Joke(751, "Why did the musician go to jail?", "For getting into treble!"),
            Joke(752, "What do you call a singing laptop?", "A Dell!"),
            Joke(753, "Why did the piano break up with the accordion?", "It was too pushy!"),
            Joke(754, "What do you call a fish that plays guitar?", "A bass player!"),
            Joke(755, "Why did the drum feel beat?", "Always getting hit!"),
            Joke(756, "What do you call a sleeping guitar?", "Acoustic!"),
            Joke(757, "Why did the violin feel stressed?", "Too much pressure!"),
            Joke(758, "What do you call a trumpet that works out?", "Horned and toned!"),
            Joke(759, "Why did the flute feel airy?", "Full of wind!"),
            Joke(760, "What do you call a DJ who gardens?", "A turnip mixer!"),
            Joke(761, "Why did the singer lose their voice?", "Too many high notes!"),
            Joke(762, "What do you call a choir that's cold?", "A brrr-tone chorus!"),
            Joke(763, "Why did the opera feel dramatic?", "High stakes singing!"),
            Joke(764, "What do you call a rapper who bakes?", "A dough boy!"),
            Joke(765, "Why did the rock band feel solid?", "Hard as stone!"),
            Joke(766, "What do you call a country singer's truck?", "Honky tonk mobile!"),
            Joke(767, "Why did the jazz musician feel smooth?", "Cool notes!"),
            Joke(768, "What do you call classical music lovers?", "Orchestra-ted!"),
            Joke(769, "Why did the pop song feel catchy?", "Ear worm!"),
            Joke(770, "What do you call heavy metal fans?", "Headbangers!"),
            Joke(771, "Why did the movie feel watched?", "So many viewers!"),
            Joke(772, "What do you call a film without sound?", "Silent treatment!"),
            Joke(773, "Why did the sequel feel repetitive?", "Here we go again!"),
            Joke(774, "What do you call a prequel?", "Before the beginning!"),
            Joke(775, "Why did the remake feel familiar?", "Seen it before!"),
            Joke(776, "What do you call a spin-off?", "Side story!"),
            Joke(777, "Why did the documentary feel real?", "True story!"),
            Joke(778, "What do you call an animated movie?", "Drawn conclusion!"),
            Joke(779, "Why did the horror film feel scary?", "Fright night!"),
            Joke(780, "What do you call a comedy that's not funny?", "Awkward silence!"),
            Joke(781, "Why did the drama feel emotional?", "Tears guaranteed!"),
            Joke(782, "What do you call an action movie?", "Explosion fest!"),
            Joke(783, "Why did the romance feel cheesy?", "Love is corny!"),
            Joke(784, "What do you call a thriller?", "Edge of seat!"),
            Joke(785, "Why did the sci-fi feel futuristic?", "Space age stuff!"),
            Joke(786, "What do you call a fantasy film?", "Magic on screen!"),
            Joke(787, "Why did the musical feel catchy?", "Song and dance!"),
            Joke(788, "What do you call a Western movie?", "Cowboy time!"),
            Joke(789, "Why did the superhero movie feel powerful?", "Cape crusaders!"),
            Joke(790, "What do you call a villain origin story?", "Bad beginning!"),
            Joke(791, "Why did the TV show feel addictive?", "Binge worthy!"),
            Joke(792, "What do you call a series finale?", "The end... or is it?"),
            Joke(793, "Why did the sitcom feel funny?", "Laugh track!"),
            Joke(794, "What do you call a reality show?", "Unreal reality!"),
            Joke(795, "Why did the talk show feel chatty?", "Interview central!"),
            Joke(796, "What do you call a game show?", "Prize time!"),
            Joke(797, "Why did the soap opera feel dramatic?", "Plot twist!"),
            Joke(798, "What do you call a miniseries?", "Short commitment!"),
            Joke(799, "Why did the streaming service feel convenient?", "Watch anytime!"),
            Joke(800, "What do you call cable cutting?", "Freedom from bundles!"),
            Joke(801, "Why did the actor feel dramatic?", "Always performing!"),
            Joke(802, "What do you call a method actor?", "Too into it!"),
            Joke(803, "Why did the director feel bossy?", "Calling the shots!"),
            Joke(804, "What do you call a producer?", "Money maker!"),
            Joke(805, "Why did the screenwriter feel written out?", "Script problems!"),
            Joke(806, "What do you call a stunt double?", "Risk taker!"),
            Joke(807, "Why did the extras feel background?", "Scenery people!"),
            Joke(808, "What do you call a movie premiere?", "Red carpet time!"),
            Joke(809, "Why did the award show feel long?", "Speech after speech!"),
            Joke(810, "What do you call an Oscar?", "Gold man trophy!"),
            Joke(811, "Why did the comedian feel funny?", "Joke maker!"),
            Joke(812, "What do you call a stand-up special?", "Mic night!"),
            Joke(813, "Why did the improv feel unscripted?", "Making it up!"),
            Joke(814, "What do you call a sketch comedy?", "Quick bits!"),
            Joke(815, "Why did the roast feel burnt?", "Insult fest!"),
            Joke(816, "What do you call a podcast?", "Talk in your ears!"),
            Joke(817, "Why did the audiobook feel read?", "Listening literature!"),
            Joke(818, "What do you call a concert?", "Live music magic!"),
            Joke(819, "Why did the festival feel crowded?", "People everywhere!"),
            Joke(820, "What do you call a front row seat?", "Up close personal!"),
            Joke(821, "Why did the backstage feel exclusive?", "VIP access!"),
            Joke(822, "What do you call a meet and greet?", "Fan moment!"),
            Joke(823, "Why did the autograph feel special?", "Personal signature!"),
            Joke(824, "What do you call concert merchandise?", "Expensive memories!"),
            Joke(825, "Why did the encore feel extra?", "One more song!"),
            Joke(826, "What do you call a sold-out show?", "Ticket luck!"),
            Joke(827, "Why did the opening act feel first?", "Warm-up crew!"),
            Joke(828, "What do you call a headliner?", "Main attraction!"),
            Joke(829, "Why did the stage dive feel risky?", "Crowd surfing!"),
            Joke(830, "What do you call a mosh pit?", "Organized chaos!"),
            Joke(831, "Why did the theater feel dramatic?", "Live performance!"),
            Joke(832, "What do you call a Broadway show?", "Big stage dreams!"),
            Joke(833, "Why did the musical feel sung?", "Everything's a song!"),
            Joke(834, "What do you call a play?", "Acting live!"),
            Joke(835, "Why did the intermission feel needed?", "Bathroom break!"),
            Joke(836, "What do you call a standing ovation?", "Earned applause!"),
            Joke(837, "Why did the curtain call feel final?", "Take a bow!"),
            Joke(838, "What do you call a matinee?", "Afternoon show!"),
            Joke(839, "Why did the evening show feel late?", "Night entertainment!"),
            Joke(840, "What do you call a dinner theater?", "Eat and watch!"),
            Joke(841, "Why did the magic show feel tricky?", "Illusion confusion!"),
            Joke(842, "What do you call a circus?", "Ring of wonder!"),
            Joke(843, "Why did the acrobat feel flippy?", "Upside down life!"),
            Joke(844, "What do you call a tightrope walker?", "Balance master!"),
            Joke(845, "Why did the juggler feel busy?", "Hands full!"),
            Joke(846, "What do you call a fire breather?", "Hot talent!"),
            Joke(847, "Why did the mime feel silent?", "No words needed!"),
            Joke(848, "What do you call a ventriloquist?", "Two voices one person!"),
            Joke(849, "Why did the puppet show feel stringy?", "Controlled performance!"),
            Joke(850, "What do you call a variety show?", "Mixed entertainment!"),
            
            // Weather and Seasons Jokes (851-900)
            Joke(851, "Why did the weather report feel uncertain?", "Chance of everything!"),
            Joke(852, "What do you call a sunny day?", "Vitamin D time!"),
            Joke(853, "Why did the rain feel wet?", "Obvious observation!"),
            Joke(854, "What do you call a rainbow?", "Sky painting!"),
            Joke(855, "Why did the thunder feel loud?", "Nature's drums!"),
            Joke(856, "What do you call lightning?", "Electric sky!"),
            Joke(857, "Why did the fog feel mysterious?", "Can't see clearly!"),
            Joke(858, "What do you call a blizzard?", "Snow overload!"),
            Joke(859, "Why did the heat wave feel hot?", "Sweating season!"),
            Joke(860, "What do you call a cold front?", "Chill incoming!"),
            Joke(861, "Why did spring feel new?", "Fresh beginnings!"),
            Joke(862, "What do you call blooming flowers?", "Nature's wake-up!"),
            Joke(863, "Why did April showers feel wet?", "May flowers coming!"),
            Joke(864, "What do you call baby birds?", "Chirp squad!"),
            Joke(865, "Why did allergies feel sneezy?", "Pollen attack!"),
            Joke(866, "What do you call summer vacation?", "Freedom season!"),
            Joke(867, "Why did the pool feel refreshing?", "Beat the heat!"),
            Joke(868, "What do you call a barbecue?", "Grill time!"),
            Joke(869, "Why did fireflies feel magical?", "Nature's lights!"),
            Joke(870, "What do you call a sunburn?", "Too much fun!"),
            Joke(871, "Why did fall feel colorful?", "Leaf change!"),
            Joke(872, "What do you call pumpkin spice?", "Autumn flavor!"),
            Joke(873, "Why did apple picking feel seasonal?", "Orchard time!"),
            Joke(874, "What do you call a hay ride?", "Farm transportation!"),
            Joke(875, "Why did the scarecrow feel important?", "Crow control!"),
            Joke(876, "What do you call winter wonderland?", "Snow paradise!"),
            Joke(877, "Why did hot chocolate feel cozy?", "Warm comfort!"),
            Joke(878, "What do you call a snowman?", "Frozen friend!"),
            Joke(879, "Why did the fireplace feel toasty?", "Indoor warmth!"),
            Joke(880, "What do you call cabin fever?", "Indoor restlessness!"),
            Joke(881, "Why did the umbrella feel useful?", "Rain shield!"),
            Joke(882, "What do you call galoshes?", "Puddle jumpers!"),
            Joke(883, "Why did the raincoat feel waterproof?", "Dry inside!"),
            Joke(884, "What do you call a mud puddle?", "Splash zone!"),
            Joke(885, "Why did the wind feel breezy?", "Air in motion!"),
            Joke(886, "What do you call a tornado?", "Spinning danger!"),
            Joke(887, "Why did the hurricane feel windy?", "Storm surge!"),
            Joke(888, "What do you call a drought?", "Water waiting!"),
            Joke(889, "Why did the flood feel rising?", "Water everywhere!"),
            Joke(890, "What do you call an earthquake?", "Ground shaking!"),
            Joke(891, "Why did the weatherman feel wrong?", "Prediction problems!"),
            Joke(892, "What do you call a barometer?", "Pressure reader!"),
            Joke(893, "Why did the thermometer feel hot?", "Temperature tales!"),
            Joke(894, "What do you call a wind vane?", "Direction finder!"),
            Joke(895, "Why did the rain gauge feel full?", "Measuring drops!"),
            Joke(896, "What do you call the solstice?", "Day length extreme!"),
            Joke(897, "Why did the equinox feel balanced?", "Equal day night!"),
            Joke(898, "What do you call daylight savings?", "Time confusion!"),
            Joke(899, "Why did the groundhog feel watched?", "Shadow pressure!"),
            Joke(900, "What do you call an Indian summer?", "Warm surprise!"),
            
            // Miscellaneous Classic Jokes (901-1000)
            Joke(901, "Why did the light bulb feel bright?", "Ideas glowing!"),
            Joke(902, "What do you call a doorbell that doesn't work?", "Knock knock!"),
            Joke(903, "Why did the mirror feel reflective?", "Self-absorbed!"),
            Joke(904, "What do you call a broken clock?", "Right twice daily!"),
            Joke(905, "Why did the candle feel lit?", "Burning bright!"),
            Joke(906, "What do you call an old battery?", "No charge!"),
            Joke(907, "Why did the key feel important?", "Unlocking potential!"),
            Joke(908, "What do you call a squeaky door?", "Oil me please!"),
            Joke(909, "Why did the window feel transparent?", "See through!"),
            Joke(910, "What do you call a stubborn door?", "Won't budge!"),
            Joke(911, "Why did the book feel read?", "Cover to cover!"),
            Joke(912, "What do you call a bookmark?", "Place holder!"),
            Joke(913, "Why did the library feel quiet?", "Shh zone!"),
            Joke(914, "What do you call a speed reader?", "Page turner!"),
            Joke(915, "Why did the newspaper feel old?", "Yesterday's news!"),
            Joke(916, "What do you call a pen pal?", "Distance friend!"),
            Joke(917, "Why did the diary feel private?", "Secret keeper!"),
            Joke(918, "What do you call a bucket list?", "Dream goals!"),
            Joke(919, "Why did the to-do list feel long?", "Never ending!"),
            Joke(920, "What do you call a shopping list?", "Memory aid!"),
            Joke(921, "Why did the dentist feel toothy?", "Smile specialist!"),
            Joke(922, "What do you call a haircut?", "Snip snip!"),
            Joke(923, "Why did the diet feel hungry?", "Eating less!"),
            Joke(924, "What do you call a gym membership?", "Guilt card!"),
            Joke(925, "Why did the checkup feel healthy?", "Doctor says so!"),
            Joke(926, "What do you call a vitamin?", "Pill of goodness!"),
            Joke(927, "Why did the bandage feel sticky?", "Wound protector!"),
            Joke(928, "What do you call medicine?", "Feel better liquid!"),
            Joke(929, "Why did the sunscreen feel protective?", "UV blocker!"),
            Joke(930, "What do you call moisturizer?", "Skin drink!"),
            Joke(931, "Why did the joke teller feel funny?", "Laugh maker!"),
            Joke(932, "What do you call a pun?", "Word play!"),
            Joke(933, "Why did the riddle feel tricky?", "Brain teaser!"),
            Joke(934, "What do you call a knock knock joke?", "Door humor!"),
            Joke(935, "Why did the dad joke feel punny?", "Father's specialty!"),
            Joke(936, "What do you call sarcasm?", "Witty words!"),
            Joke(937, "Why did the roast feel burned?", "Friendly fire!"),
            Joke(938, "What do you call irony?", "Unexpected twist!"),
            Joke(939, "Why did the comedy feel timed?", "Delivery matters!"),
            Joke(940, "What do you call a heckler?", "Crowd annoyance!"),
            Joke(941, "Why did the optimist feel positive?", "Glass half full!"),
            Joke(942, "What do you call a pessimist?", "Glass half empty!"),
            Joke(943, "Why did the realist feel balanced?", "It's just a glass!"),
            Joke(944, "What do you call an opportunist?", "I'll drink that!"),
            Joke(945, "Why did procrastination feel later?", "I'll do it tomorrow!"),
            Joke(946, "What do you call overthinking?", "Brain spiral!"),
            Joke(947, "Why did nostalgia feel old?", "Good old days!"),
            Joke(948, "What do you call déjà vu?", "Haven't we done this?"),
            Joke(949, "Why did karma feel earned?", "What goes around!"),
            Joke(950, "What do you call fate?", "Meant to be!"),
            Joke(951, "Why did the sunrise feel early?", "Day starter!"),
            Joke(952, "What do you call a sunset?", "Day ender!"),
            Joke(953, "Why did the moon feel lunar?", "Night light!"),
            Joke(954, "What do you call stars at night?", "Space sparkles!"),
            Joke(955, "Why did the galaxy feel vast?", "Universe big!"),
            Joke(956, "What do you call infinity?", "Never ending!"),
            Joke(957, "Why did zero feel empty?", "Nothing there!"),
            Joke(958, "What do you call everything?", "The whole thing!"),
            Joke(959, "Why did something feel important?", "Better than nothing!"),
            Joke(960, "What do you call nothing?", "Absence of all!"),
            Joke(961, "Why did the question feel asked?", "Inquiry made!"),
            Joke(962, "What do you call an answer?", "Response given!"),
            Joke(963, "Why did the problem feel solved?", "Solution found!"),
            Joke(964, "What do you call a mystery?", "Unknown unknown!"),
            Joke(965, "Why did the secret feel hidden?", "Shh don't tell!"),
            Joke(966, "What do you call a reveal?", "Surprise shown!"),
            Joke(967, "Why did the truth feel honest?", "No lies here!"),
            Joke(968, "What do you call a white lie?", "Kind fib!"),
            Joke(969, "Why did the promise feel kept?", "Word honored!"),
            Joke(970, "What do you call a pinky swear?", "Unbreakable bond!"),
            Joke(971, "Why did the handshake feel formal?", "Deal sealed!"),
            Joke(972, "What do you call a high five?", "Hand celebration!"),
            Joke(973, "Why did the hug feel warm?", "Embrace given!"),
            Joke(974, "What do you call a wave?", "Distance greeting!"),
            Joke(975, "Why did the smile feel happy?", "Joy expressed!"),
            Joke(976, "What do you call a frown?", "Sad face!"),
            Joke(977, "Why did the laugh feel good?", "Joy released!"),
            Joke(978, "What do you call happy tears?", "Joy overflow!"),
            Joke(979, "Why did the yawn feel contagious?", "Sleepy spread!"),
            Joke(980, "What do you call a sneeze?", "Achoo moment!"),
            Joke(981, "Why did the hiccup feel annoying?", "Won't stop!"),
            Joke(982, "What do you call a burp?", "Excuse me!"),
            Joke(983, "Why did the cough feel scratchy?", "Throat tickle!"),
            Joke(984, "What do you call a sigh?", "Breath of relief!"),
            Joke(985, "Why did the whisper feel quiet?", "Secret voice!"),
            Joke(986, "What do you call a shout?", "Loud voice!"),
            Joke(987, "Why did the song feel musical?", "Melody made!"),
            Joke(988, "What do you call humming?", "Wordless tune!"),
            Joke(989, "Why did the whistle feel airy?", "Lips and air!"),
            Joke(990, "What do you call clapping?", "Hand applause!"),
            Joke(991, "Why did the stomping feel loud?", "Floor pounding!"),
            Joke(992, "What do you call snapping?", "Finger click!"),
            Joke(993, "Why did the tapping feel rhythmic?", "Beat keeping!"),
            Joke(994, "What do you call a dance?", "Body music!"),
            Joke(995, "Why did the skip feel bouncy?", "Happy hop!"),
            Joke(996, "What do you call a jump?", "Ground leaving!"),
            Joke(997, "Why did the spin feel dizzy?", "Round and round!"),
            Joke(998, "What do you call a bow?", "Respect shown!"),
            Joke(999, "Why did the curtsy feel fancy?", "Royal greeting!"),
            Joke(1000, "What do you call the end?", "The grand finale!")
        )
    }
}
